import { supabase } from "@/lib/supabase";
import { Artwork, Exhibition } from "@/types";
import { v4 as uuidv4 } from 'uuid';

export function useAdminActions() {

    // Helper: Upload Image to Supabase Storage
    const uploadImage = async (file: File) => {
        const fileExt = file.name.split('.').pop();
        const fileName = `${uuidv4()}.${fileExt}`;
        const filePath = `${fileName}`;

        const { error: uploadError } = await supabase.storage
            .from('images')
            .upload(filePath, file);

        if (uploadError) {
            throw uploadError;
        }

        const { data } = supabase.storage.from('images').getPublicUrl(filePath);
        return data.publicUrl;
    };

    // Artwork Actions
    const createArtwork = async (data: Omit<Artwork, 'id' | 'createdAt'>) => {
        // Convert camelCase to snake_case for DB
        const { error } = await supabase.from('artworks').insert({
            title: data.title,
            artist: data.artist,
            year: data.year,
            medium: data.medium,
            dimensions: data.dimensions,
            description: data.description,
            image_url: data.imageUrl,
            // id is auto-generated by gen_random_uuid(), created_at by default
        });

        if (error) throw error;
        return true;
    };

    const deleteArtwork = async (id: string) => {
        const { error } = await supabase.from('artworks').delete().eq('id', id);
        if (error) throw error;
    };

    // Exhibition Actions
    const createExhibition = async (data: Omit<Exhibition, 'id' | 'createdAt' | 'isActive'>) => {
        const { error } = await supabase.from('exhibitions').insert({
            title: data.title,
            description: data.description,
            start_date: data.startDate,
            end_date: data.endDate,
            is_active: false,
            artwork_ids: []
        });

        if (error) throw error;
        return true;
    };

    const setExhibitionActive = async (id: string) => {
        // 1. Set all to inactive
        // We use a "not equal to impossible ID" hack to try and update all rows, 
        // or we could skip this if we assume the backend handles it, but for now client-side safety:
        await supabase.from('exhibitions').update({ is_active: false }).neq('id', '00000000-0000-0000-0000-000000000000');

        // 2. Set target to active
        const { error } = await supabase.from('exhibitions').update({ is_active: true }).eq('id', id);
        if (error) throw error;
    };

    const updateExhibitionArtworks = async (id: string, artworkIds: string[]) => {
        const { error } = await supabase
            .from('exhibitions')
            .update({ artwork_ids: artworkIds })
            .eq('id', id);
        if (error) throw error;
    };

    const deleteExhibition = async (id: string) => {
        const { error } = await supabase.from('exhibitions').delete().eq('id', id);
        if (error) throw error;
    };

    // Deprecated but kept for type signature compatibility if needed
    const exportDatabase = async () => { return ""; };
    const importDatabase = async (s: string) => { return true; };

    return {
        createArtwork,
        deleteArtwork,
        createExhibition,
        setExhibitionActive,
        updateExhibitionArtworks,
        deleteExhibition,
        uploadImage,
        exportDatabase,
        importDatabase
    };
}
